version: "3.7"

services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - "8099:8099"
    environment:
      - LISTEN_PORT=8099
      - SITE_HEADER=Dev SAML Image
    volumes:
      - ./metadata/:/var/www/metadata/
      - ./config/:/var/www/config/
      - ./modules/totara/:/var/www/html/modules/totara/
    networks:
      - totara-saml
    extra_hosts:
      - "totara.local:host-gateway"
      - "development.totara.local:host-gateway"
      - "testing.totara.local:host-gateway"
      - "totara.behat:host-gateway"

  prod:
    build: .
    ports:
      - "8098:8098"
    environment:
      - LISTEN_PORT=8098
      - SITE_HEADER=Prod SAML Image

networks:
  totara-saml:
    name: totara-saml

