version: "3.7"

services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - "8099:8099"
    environment:
      - LISTEN_PORT=8099
      - SITE_HEADER=Dev SAML Image
    volumes:
      - ./metadata/:/var/www/html/metadata/
      - ./config/:/var/www/config/
      - ./modules/totara/:/var/www/html/modules/totara/

  prod:
    build: .
    ports:
      - "8098:8098"
    environment:
      - LISTEN_PORT=8098
      - SITE_HEADER=Prod SAML Image
